### ISSUE TITLE
Cannot npm install on macOS or linux

### ISSUE THREAD

**Issue by wesleyguirra** [xdenser/node-firebird-libfbclient#107]
I'm having a issue with installation on macOS Catalina and ubuntu the error log is this:

```
2 warnings generated.
  SOLINK_MODULE(target) Release/binding.node
ld: warning: directory not found for option '-L/Library/Frameworks/Firebird.framework/Libraries/'
ld: library not found for -lfbclient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/wesleyguirra/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/wesleyguirra/.nvm/versions/node/v10.15.3/bin/node" "/Users/wesleyguirra/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wesleyguirra/Development/atria-api-node/node_modules/firebird
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebird@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebird@0.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wesleyguirra/.npm/_logs/2020-07-01T12_01_43_363Z-debug.log
```

Someone is having this issue, can help me?

**Comment by wesleyguirra** [comment]
@xdenser

**Comment by erokshark** [comment]
Try this:

npm install --global --production windows-build-tools

**Comment by NicoAiko** [comment]
@wesleyguirra You need the Firebird Server/Client installed on your machine.

@erokshark This doesn't do on macOS/Linux.

**Comment by wesleyguirra** [comment]
@erokshark  I was using macOS with docker.

@NicoAiko  I was using docker with linux image with the firebird installed.

**Comment by NicoAiko** [comment]
> @erokshark I was using macOS with docker.
> 
> @NicoAiko I was using docker with linux image with the firebird installed.

From your error log it seems you try to use this package on macOS. Even if you have a docker image with firebird installed where your database is located, (I do the same by the way) you still need to install the Firebird Server on MacOS so you have the native libclient that is necessary to compile the node plugin.

**Comment by wesleyguirra** [comment]
Ok, understood. Thank you!
