### ISSUE TITLE
Build issue v0.11.13

### ISSUE THREAD

**Issue by EvanCarroll** [xdenser/node-firebird-libfbclient#31]
```
npm http GET https://registry.npmjs.org/firebird
npm http 304 https://registry.npmjs.org/firebird

> firebird@0.0.10 install /home/ecarroll/code/vince/express/node_modules/firebird
> node-gyp rebuild

make: Entering directory `/home/ecarroll/code/vince/express/node_modules/firebird/build'
  CXX(target) Release/obj.target/binding/src/fb-bindings.o
In file included from ../src/./fb-bindings-connection.h:13:0,
                 from ../src/fb-bindings.cc:14:
../src/././fb-bindings-fbeventemitter.h:18:41: error: expected class-name before ‘{’ token
 class FBEventEmitter: public ObjectWrap {
                                         ^
../src/././fb-bindings-fbeventemitter.h:33:29: error: ‘AccessorInfo’ does not name a type
                       const AccessorInfo &info);
                             ^
../src/././fb-bindings-fbeventemitter.h:33:43: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
                       const AccessorInfo &info);
                                           ^
In file included from ../src/./fb-bindings-connection.h:15:0,
                 from ../src/fb-bindings.cc:14:
../src/././fb-bindings-blob.h:31:13: error: ‘Arguments’ does not name a type
   New(const Arguments& args);
             ^
../src/././fb-bindings-blob.h:31:24: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   New(const Arguments& args);
                        ^
../src/././fb-bindings-blob.h:34:18: error: ‘Arguments’ does not name a type
   ReadSync(const Arguments& args);
                  ^
../src/././fb-bindings-blob.h:34:29: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   ReadSync(const Arguments& args);
                             ^
../src/././fb-bindings-blob.h:50:14: error: ‘Arguments’ does not name a type
   Read(const Arguments& args);
              ^
../src/././fb-bindings-blob.h:50:25: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Read(const Arguments& args);
                         ^
../src/././fb-bindings-blob.h:53:18: error: ‘Arguments’ does not name a type
   OpenSync(const Arguments& args);
                  ^
../src/././fb-bindings-blob.h:53:29: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   OpenSync(const Arguments& args);
                             ^
../src/././fb-bindings-blob.h:56:19: error: ‘Arguments’ does not name a type
   CloseSync(const Arguments& args);
                   ^
../src/././fb-bindings-blob.h:56:30: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   CloseSync(const Arguments& args);
                              ^
../src/././fb-bindings-blob.h:59:19: error: ‘Arguments’ does not name a type
   WriteSync(const Arguments& args);
                   ^
../src/././fb-bindings-blob.h:59:30: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   WriteSync(const Arguments& args);
                              ^
../src/././fb-bindings-blob.h:66:15: error: ‘Arguments’ does not name a type
   Write(const Arguments& args);
               ^
../src/././fb-bindings-blob.h:66:26: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Write(const Arguments& args);
                          ^
../src/././fb-bindings-blob.h:71:29: error: ‘AccessorInfo’ does not name a type
                       const AccessorInfo &info);
                             ^
../src/././fb-bindings-blob.h:71:43: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
                       const AccessorInfo &info);
                                           ^
In file included from ../src/fb-bindings.cc:14:0:
../src/./fb-bindings-connection.h:56:14: error: ‘Arguments’ does not name a type
   New (const Arguments& args);
              ^
../src/./fb-bindings-connection.h:56:25: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   New (const Arguments& args);
                         ^
../src/./fb-bindings-connection.h:59:22: error: ‘Arguments’ does not name a type
   ConnectSync (const Arguments& args);
                      ^
../src/./fb-bindings-connection.h:59:33: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   ConnectSync (const Arguments& args);
                                 ^
../src/./fb-bindings-connection.h:76:18: error: ‘Arguments’ does not name a type
   Connect (const Arguments& args);
                  ^
../src/./fb-bindings-connection.h:76:29: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Connect (const Arguments& args);
                             ^
../src/./fb-bindings-connection.h:79:20: error: ‘Arguments’ does not name a type
   Disconnect(const Arguments& args);
                    ^
../src/./fb-bindings-connection.h:79:31: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Disconnect(const Arguments& args);
                               ^
../src/./fb-bindings-connection.h:82:45: error: ‘AccessorInfo’ does not name a type
                                       const AccessorInfo &info);
                                             ^
../src/./fb-bindings-connection.h:82:59: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
                                       const AccessorInfo &info);
                                                           ^
../src/./fb-bindings-connection.h:86:29: error: ‘AccessorInfo’ does not name a type
                       const AccessorInfo &info);
                             ^
../src/./fb-bindings-connection.h:86:43: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
                       const AccessorInfo &info);
                                           ^
../src/./fb-bindings-connection.h:89:21: error: ‘Arguments’ does not name a type
   CommitSync (const Arguments& args);
                     ^
../src/./fb-bindings-connection.h:89:32: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   CommitSync (const Arguments& args);
                                ^
../src/./fb-bindings-connection.h:92:23: error: ‘Arguments’ does not name a type
   RollbackSync (const Arguments& args);
                       ^
../src/./fb-bindings-connection.h:92:34: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   RollbackSync (const Arguments& args);
                                  ^
../src/./fb-bindings-connection.h:95:20: error: ‘Arguments’ does not name a type
   StartSync (const Arguments& args);
                    ^
../src/./fb-bindings-connection.h:95:31: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   StartSync (const Arguments& args);
                               ^
../src/./fb-bindings-connection.h:115:17: error: ‘Arguments’ does not name a type
   Commit (const Arguments& args);
                 ^
../src/./fb-bindings-connection.h:115:28: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Commit (const Arguments& args);
                            ^
../src/./fb-bindings-connection.h:118:19: error: ‘Arguments’ does not name a type
   Rollback (const Arguments& args);
                   ^
../src/./fb-bindings-connection.h:118:30: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Rollback (const Arguments& args);
                              ^
../src/./fb-bindings-connection.h:121:16: error: ‘Arguments’ does not name a type
   Start (const Arguments& args);
                ^
../src/./fb-bindings-connection.h:121:27: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Start (const Arguments& args);
                           ^
../src/./fb-bindings-connection.h:124:19: error: ‘Arguments’ does not name a type
   QuerySync(const Arguments& args);
                   ^
../src/./fb-bindings-connection.h:124:30: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   QuerySync(const Arguments& args);
                              ^
../src/./fb-bindings-connection.h:141:15: error: ‘Arguments’ does not name a type
   Query(const Arguments& args);
               ^
../src/./fb-bindings-connection.h:141:26: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Query(const Arguments& args);
                          ^
../src/./fb-bindings-connection.h:144:18: error: ‘Arguments’ does not name a type
   addEvent(const Arguments& args);
                  ^
../src/./fb-bindings-connection.h:144:29: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   addEvent(const Arguments& args);
                             ^
../src/./fb-bindings-connection.h:147:21: error: ‘Arguments’ does not name a type
   deleteEvent(const Arguments& args);
                     ^
../src/./fb-bindings-connection.h:147:32: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   deleteEvent(const Arguments& args);
                                ^
../src/./fb-bindings-connection.h:150:22: error: ‘Arguments’ does not name a type
   PrepareSync (const Arguments& args);
                      ^
../src/./fb-bindings-connection.h:150:33: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   PrepareSync (const Arguments& args);
                                 ^
../src/./fb-bindings-connection.h:153:22: error: ‘Arguments’ does not name a type
   NewBlobSync (const Arguments& args);
                      ^
../src/./fb-bindings-connection.h:153:33: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   NewBlobSync (const Arguments& args);
                                 ^
In file included from ../src/fb-bindings.cc:15:0:
../src/./fb-bindings-fbresult.h:36:55: error: ‘Arguments’ does not name a type
  static Handle<Value> set_params(XSQLDA *sqlda, const Arguments& args);
                                                       ^
../src/./fb-bindings-fbresult.h:36:66: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static Handle<Value> set_params(XSQLDA *sqlda, const Arguments& args);
                                                                  ^
../src/./fb-bindings-fbresult.h:41:14: error: ‘Arguments’ does not name a type
   New (const Arguments& args);
              ^
../src/./fb-bindings-fbresult.h:41:25: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   New (const Arguments& args);
                         ^
../src/./fb-bindings-fbresult.h:48:19: error: ‘Arguments’ does not name a type
   FetchSync(const Arguments& args);
                   ^
../src/./fb-bindings-fbresult.h:48:30: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   FetchSync(const Arguments& args);
                              ^
../src/./fb-bindings-fbresult.h:65:15: error: ‘Arguments’ does not name a type
   Fetch(const Arguments& args);
               ^
../src/./fb-bindings-fbresult.h:65:26: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
   Fetch(const Arguments& args);
                          ^
In file included from ../src/fb-bindings.cc:19:0:
../src/./fb-bindings-statement.h:28:13: error: ‘Arguments’ does not name a type
  New (const Arguments& args);
             ^
../src/./fb-bindings-statement.h:28:24: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  New (const Arguments& args);
                        ^
../src/./fb-bindings-statement.h:31:18: error: ‘Arguments’ does not name a type
  ExecSync (const Arguments& args);
                  ^
../src/./fb-bindings-statement.h:31:29: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  ExecSync (const Arguments& args);
                             ^
../src/./fb-bindings-statement.h:43:14: error: ‘Arguments’ does not name a type
  Exec (const Arguments& args);
              ^
../src/./fb-bindings-statement.h:43:25: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  Exec (const Arguments& args);
                         ^
In file included from ../src/././fb-bindings.h:10:0,
                 from ../src/./fb-bindings-connection.h:12,
                 from ../src/fb-bindings.cc:14:
/home/ecarroll/.node-gyp/0.11.13/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/ecarroll/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/fb-bindings.cc:46:15: error: within this context
   HandleScope scope;
               ^
make: *** [Release/obj.target/binding/src/fb-bindings.o] Error 1
make: Leaving directory `/home/ecarroll/code/vince/express/node_modules/firebird/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.13.0-27-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ecarroll/code/vince/express/node_modules/firebird
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! firebird@0.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firebird@0.0.10 install script.
npm ERR! This is most likely a problem with the firebird package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls firebird
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-27-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "firebird"
npm ERR! cwd /home/ecarroll/code/vince/express
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ecarroll/code/vince/express/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mariuz** [comment]
v0.11 was unstable , this can be closed
