### ISSUE TITLE
FBStatement cannot be reused after rollback/commit

### ISSUE THREAD

**Issue by heri16** [xdenser/node-firebird-libfbclient#64]
Calling execSync again against the same FBStatement object causes crash:

> Error: In FBStatement::execSync, free_statement - Dynamic SQL Error
> SQL error code = -501
> Attempt to reclose a closed cursor

```
at Error (native)
at Session.fetchItemAnalysis (D:\slackbot\accurate_db.js:79:17)
at Object.convo.ask.callback (D:\slackbot\slack_bot.js:265:35)
at Conversation.handle (D:\slackbot\node_modules\botkit\lib\CoreBot.js:129:41)
at D:\slackbot\node_modules\botkit\lib\CoreBot.js:980:31
at Object.bot.findConversation (D:\slackbot\node_modules\botkit\lib\Slackbot_worker.js:657:25)
at D:\slackbot\node_modules\botkit\lib\CoreBot.js:978:21
at next (D:\slackbot\node_modules\botkit\node_modules\ware\lib\index.js:82:27)
at Ware.run (D:\slackbot\node_modules\botkit\node_modules\ware\lib\index.js:88:3)
at Object.Botkit.botkit.receiveMessage (D:\slackbot\node_modules\botkit\lib\CoreBot.js:973:35)
```

**Comment by heri16** [comment]
Steps to reproduce:

FBStatement.execSync() -> connection.rollback() -> FBStatement.execSync()

**Comment by xdenser** [comment]
use FBStatement.execSync() -> connection.rollback() ->connection.startTransactionSync() -> FBStatement.execSync()
