### ISSUE TITLE
Cannot install the firebird!

### ISSUE THREAD

**Issue by JefterRocha** [xdenser/node-firebird-libfbclient#86]
I try to install the package but something wrong is happening!
My SO: WIndows 10

Log
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'firebird' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose npm-session 97c6efdd8e5ff528
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/firebird 105ms (from cache)
8 silly pacote range manifest for firebird@* fetched in 142ms
9 timing stage:loadCurrentTree Completed in 884ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 53ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule firebird@0.1.2 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/nan 49ms (from cache)
18 silly pacote range manifest for nan@^2.0.9 fetched in 55ms
19 silly resolveWithNewModule nan@2.11.1 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 205ms
21 timing stage:loadIdealTree Completed in 319ms
22 silly currentTree node-fb-sample@0.0.2
22 silly currentTree +-- accepts@1.3.5
22 silly currentTree +-- array-flatten@1.1.1
22 silly currentTree +-- body-parser@1.18.3
22 silly currentTree +-- bytes@3.0.0
22 silly currentTree +-- content-disposition@0.5.2
22 silly currentTree +-- content-type@1.0.4
22 silly currentTree +-- cookie-signature@1.0.6
22 silly currentTree +-- cookie@0.3.1
22 silly currentTree +-- debug@2.6.9
22 silly currentTree +-- depd@1.1.2
22 silly currentTree +-- destroy@1.0.4
22 silly currentTree +-- ee-first@1.1.1
22 silly currentTree +-- encodeurl@1.0.2
22 silly currentTree +-- escape-html@1.0.3
22 silly currentTree +-- etag@1.8.1
22 silly currentTree +-- express@4.16.4
22 silly currentTree | `-- statuses@1.4.0
22 silly currentTree +-- finalhandler@1.1.1
22 silly currentTree | `-- statuses@1.4.0
22 silly currentTree +-- forwarded@0.1.2
22 silly currentTree +-- fresh@0.5.2
22 silly currentTree +-- http-errors@1.6.3
22 silly currentTree +-- iconv-lite@0.4.23
22 silly currentTree +-- inherits@2.0.3
22 silly currentTree +-- ipaddr.js@1.8.0
22 silly currentTree +-- media-typer@0.3.0
22 silly currentTree +-- merge-descriptors@1.0.1
22 silly currentTree +-- methods@1.1.2
22 silly currentTree +-- mime-db@1.37.0
22 silly currentTree +-- mime-types@2.1.21
22 silly currentTree +-- mime@1.4.1
22 silly currentTree +-- ms@2.0.0
22 silly currentTree +-- negotiator@0.6.1
22 silly currentTree +-- on-finished@2.3.0
22 silly currentTree +-- parseurl@1.3.2
22 silly currentTree +-- path-to-regexp@0.1.7
22 silly currentTree +-- proxy-addr@2.0.4
22 silly currentTree +-- qs@6.5.2
22 silly currentTree +-- range-parser@1.2.0
22 silly currentTree +-- raw-body@2.3.3
22 silly currentTree +-- safe-buffer@5.1.2
22 silly currentTree +-- safer-buffer@2.1.2
22 silly currentTree +-- send@0.16.2
22 silly currentTree | `-- statuses@1.4.0
22 silly currentTree +-- serve-static@1.13.2
22 silly currentTree +-- setprototypeof@1.1.0
22 silly currentTree +-- statuses@1.5.0
22 silly currentTree +-- type-is@1.6.16
22 silly currentTree +-- unpipe@1.0.0
22 silly currentTree +-- utils-merge@1.0.1
22 silly currentTree `-- vary@1.1.2
23 silly idealTree node-fb-sample@0.0.2
23 silly idealTree +-- accepts@1.3.5
23 silly idealTree +-- array-flatten@1.1.1
23 silly idealTree +-- body-parser@1.18.3
23 silly idealTree +-- bytes@3.0.0
23 silly idealTree +-- content-disposition@0.5.2
23 silly idealTree +-- content-type@1.0.4
23 silly idealTree +-- cookie-signature@1.0.6
23 silly idealTree +-- cookie@0.3.1
23 silly idealTree +-- debug@2.6.9
23 silly idealTree +-- depd@1.1.2
23 silly idealTree +-- destroy@1.0.4
23 silly idealTree +-- ee-first@1.1.1
23 silly idealTree +-- encodeurl@1.0.2
23 silly idealTree +-- escape-html@1.0.3
23 silly idealTree +-- etag@1.8.1
23 silly idealTree +-- express@4.16.4
23 silly idealTree | `-- statuses@1.4.0
23 silly idealTree +-- finalhandler@1.1.1
23 silly idealTree | `-- statuses@1.4.0
23 silly idealTree +-- firebird@0.1.2
23 silly idealTree +-- forwarded@0.1.2
23 silly idealTree +-- fresh@0.5.2
23 silly idealTree +-- http-errors@1.6.3
23 silly idealTree +-- iconv-lite@0.4.23
23 silly idealTree +-- inherits@2.0.3
23 silly idealTree +-- ipaddr.js@1.8.0
23 silly idealTree +-- media-typer@0.3.0
23 silly idealTree +-- merge-descriptors@1.0.1
23 silly idealTree +-- methods@1.1.2
23 silly idealTree +-- mime-db@1.37.0
23 silly idealTree +-- mime-types@2.1.21
23 silly idealTree +-- mime@1.4.1
23 silly idealTree +-- ms@2.0.0
23 silly idealTree +-- nan@2.11.1
23 silly idealTree +-- negotiator@0.6.1
23 silly idealTree +-- on-finished@2.3.0
23 silly idealTree +-- parseurl@1.3.2
23 silly idealTree +-- path-to-regexp@0.1.7
23 silly idealTree +-- proxy-addr@2.0.4
23 silly idealTree +-- qs@6.5.2
23 silly idealTree +-- range-parser@1.2.0
23 silly idealTree +-- raw-body@2.3.3
23 silly idealTree +-- safe-buffer@5.1.2
23 silly idealTree +-- safer-buffer@2.1.2
23 silly idealTree +-- send@0.16.2
23 silly idealTree | `-- statuses@1.4.0
23 silly idealTree +-- serve-static@1.13.2
23 silly idealTree +-- setprototypeof@1.1.0
23 silly idealTree +-- statuses@1.5.0
23 silly idealTree +-- type-is@1.6.16
23 silly idealTree +-- unpipe@1.0.0
23 silly idealTree +-- utils-merge@1.0.1
23 silly idealTree `-- vary@1.1.2
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 26ms
26 silly diffTrees action count 2
27 silly diffTrees add nan@2.11.1
28 silly diffTrees add firebird@0.1.2
29 silly decomposeActions action count 16
30 silly decomposeActions fetch nan@2.11.1
31 silly decomposeActions extract nan@2.11.1
32 silly decomposeActions preinstall nan@2.11.1
33 silly decomposeActions build nan@2.11.1
34 silly decomposeActions install nan@2.11.1
35 silly decomposeActions postinstall nan@2.11.1
36 silly decomposeActions finalize nan@2.11.1
37 silly decomposeActions refresh-package-json nan@2.11.1
38 silly decomposeActions fetch firebird@0.1.2
39 silly decomposeActions extract firebird@0.1.2
40 silly decomposeActions preinstall firebird@0.1.2
41 silly decomposeActions build firebird@0.1.2
42 silly decomposeActions install firebird@0.1.2
43 silly decomposeActions postinstall firebird@0.1.2
44 silly decomposeActions finalize firebird@0.1.2
45 silly decomposeActions refresh-package-json firebird@0.1.2
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir C:\Users\JEFTER\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
49 timing audit compress Completed in 7ms
50 info audit Submitting payload of 3337bytes
51 verbose lock using C:\Users\JEFTER\AppData\Roaming\npm-cache\_locks\staging-9a1275d0de6ce7a5.lock for C:\Users\JEFTER\Documents\node-fb-sample\node_modules\.staging
52 silly doParallel extract 2
53 silly extract nan@2.11.1
54 silly extract firebird@0.1.2
55 silly tarball trying nan@^2.0.9 by hash: sha512-iji6k87OSXa0CcrLl9z+ZiYSuR2o+c0bGuNmXdrhTQTakxytAFsC56SArGYoiHlJlFoHSnvmhpceZJaXkVuOtA==
56 silly tarball trying firebird@* by hash: sha1-MlJd4sGMAwNrzVZnb1mbJzHfFG8=
57 silly extract nan@^2.0.9 extracted to C:\Users\JEFTER\Documents\node-fb-sample\node_modules\.staging\nan-b78063df (229ms)
58 silly extract firebird@* extracted to C:\Users\JEFTER\Documents\node-fb-sample\node_modules\.staging\firebird-62d3b5ff (362ms)
59 timing action:extract Completed in 371ms
60 silly doReverseSerial unbuild 16
61 silly doSerial remove 16
62 silly doSerial move 16
63 silly doSerial finalize 16
64 silly finalize C:\Users\JEFTER\Documents\node-fb-sample\node_modules\nan
65 silly finalize C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird
66 timing action:finalize Completed in 12ms
67 silly doParallel refresh-package-json 2
68 silly refresh-package-json C:\Users\JEFTER\Documents\node-fb-sample\node_modules\nan
69 silly refresh-package-json C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird
70 timing action:refresh-package-json Completed in 152ms
71 silly doParallel preinstall 2
72 silly preinstall nan@2.11.1
73 info lifecycle nan@2.11.1~preinstall: nan@2.11.1
74 silly preinstall firebird@0.1.2
75 info lifecycle firebird@0.1.2~preinstall: firebird@0.1.2
76 timing action:preinstall Completed in 4ms
77 silly doSerial build 16
78 silly build nan@2.11.1
79 info linkStuff nan@2.11.1
80 silly linkStuff nan@2.11.1 has C:\Users\JEFTER\Documents\node-fb-sample\node_modules as its parent node_modules
81 silly build firebird@0.1.2
82 info linkStuff firebird@0.1.2
83 silly linkStuff firebird@0.1.2 has C:\Users\JEFTER\Documents\node-fb-sample\node_modules as its parent node_modules
84 timing action:build Completed in 4ms
85 silly doSerial global-link 16
86 silly doParallel update-linked 0
87 silly doSerial install 16
88 silly install nan@2.11.1
89 info lifecycle nan@2.11.1~install: nan@2.11.1
90 silly install firebird@0.1.2
91 info lifecycle firebird@0.1.2~install: firebird@0.1.2
92 verbose lifecycle firebird@0.1.2~install: unsafe-perm in lifecycle true
93 verbose lifecycle firebird@0.1.2~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird\node_modules\.bin;C:\Users\JEFTER\Documents\node-fb-sample\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\JEFTER\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\JEFTER\AppData\Local\Programs\Python\Python37-32\;C:\Users\JEFTER\AppData\Local\Microsoft\WindowsApps;C:\Users\JEFTER\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\JEFTER\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\4.0\bin;C:\Program Files\heroku\bin;C:\Users\JEFTER\AppData\Local\Programs\we\bin;C:\Program Files\Firebird\Firebird_3_0
94 verbose lifecycle firebird@0.1.2~install: CWD: C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird
95 silly lifecycle firebird@0.1.2~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
96 timing audit submit Completed in 1442ms
97 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1441ms
98 timing audit body Completed in 0ms
99 silly lifecycle firebird@0.1.2~install: Returned: code: 1  signal: null
100 info lifecycle firebird@0.1.2~install: Failed to exec install script
101 timing action:install Completed in 1230ms
102 verbose unlock done using C:\Users\JEFTER\AppData\Roaming\npm-cache\_locks\staging-9a1275d0de6ce7a5.lock for C:\Users\JEFTER\Documents\node-fb-sample\node_modules\.staging
103 timing stage:rollbackFailedOptional Completed in 67ms
104 timing stage:runTopLevelLifecycles Completed in 3261ms
105 silly saveTree node-fb-sample@0.0.2
105 silly saveTree +-- body-parser@1.18.3
105 silly saveTree | +-- bytes@3.0.0
105 silly saveTree | +-- content-type@1.0.4
105 silly saveTree | +-- debug@2.6.9
105 silly saveTree | | `-- ms@2.0.0
105 silly saveTree | +-- depd@1.1.2
105 silly saveTree | +-- http-errors@1.6.3
105 silly saveTree | | +-- inherits@2.0.3
105 silly saveTree | | +-- setprototypeof@1.1.0
105 silly saveTree | | `-- statuses@1.5.0
105 silly saveTree | +-- iconv-lite@0.4.23
105 silly saveTree | | `-- safer-buffer@2.1.2
105 silly saveTree | +-- on-finished@2.3.0
105 silly saveTree | | `-- ee-first@1.1.1
105 silly saveTree | +-- qs@6.5.2
105 silly saveTree | +-- raw-body@2.3.3
105 silly saveTree | | `-- unpipe@1.0.0
105 silly saveTree | `-- type-is@1.6.16
105 silly saveTree |   +-- media-typer@0.3.0
105 silly saveTree |   `-- mime-types@2.1.21
105 silly saveTree |     `-- mime-db@1.37.0
105 silly saveTree +-- express@4.16.4
105 silly saveTree | +-- accepts@1.3.5
105 silly saveTree | | `-- negotiator@0.6.1
105 silly saveTree | +-- array-flatten@1.1.1
105 silly saveTree | +-- content-disposition@0.5.2
105 silly saveTree | +-- cookie-signature@1.0.6
105 silly saveTree | +-- cookie@0.3.1
105 silly saveTree | +-- encodeurl@1.0.2
105 silly saveTree | +-- escape-html@1.0.3
105 silly saveTree | +-- etag@1.8.1
105 silly saveTree | +-- finalhandler@1.1.1
105 silly saveTree | | +-- parseurl@1.3.2
105 silly saveTree | | `-- statuses@1.4.0
105 silly saveTree | +-- fresh@0.5.2
105 silly saveTree | +-- merge-descriptors@1.0.1
105 silly saveTree | +-- methods@1.1.2
105 silly saveTree | +-- parseurl@1.3.2
105 silly saveTree | +-- path-to-regexp@0.1.7
105 silly saveTree | +-- proxy-addr@2.0.4
105 silly saveTree | | +-- forwarded@0.1.2
105 silly saveTree | | `-- ipaddr.js@1.8.0
105 silly saveTree | +-- range-parser@1.2.0
105 silly saveTree | +-- safe-buffer@5.1.2
105 silly saveTree | +-- send@0.16.2
105 silly saveTree | | +-- destroy@1.0.4
105 silly saveTree | | +-- mime@1.4.1
105 silly saveTree | | `-- statuses@1.4.0
105 silly saveTree | +-- serve-static@1.13.2
105 silly saveTree | +-- statuses@1.4.0
105 silly saveTree | +-- utils-merge@1.0.1
105 silly saveTree | `-- vary@1.1.2
105 silly saveTree `-- firebird@0.1.2
105 silly saveTree   `-- nan@2.11.1
106 warn node-fb-sample@0.0.2 No license field.
107 verbose stack Error: firebird@0.1.2 install: `node-gyp rebuild`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
107 verbose stack     at emitTwo (events.js:126:13)
107 verbose stack     at EventEmitter.emit (events.js:214:7)
107 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
107 verbose stack     at emitTwo (events.js:126:13)
107 verbose stack     at ChildProcess.emit (events.js:214:7)
107 verbose stack     at maybeClose (internal/child_process.js:915:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
108 verbose pkgid firebird@0.1.2
109 verbose cwd C:\Users\JEFTER\Documents\node-fb-sample
110 verbose Windows_NT 10.0.17134
111 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "firebird"
112 verbose node v8.12.0
113 verbose npm  v6.4.1
114 error code ELIFECYCLE
115 error errno 1
116 error firebird@0.1.2 install: `node-gyp rebuild`
116 error Exit status 1
117 error Failed at the firebird@0.1.2 install script.
117 error This is probably not a problem with npm. There is likely additional logging output above.
118 verbose exit [ 1, true ]`

console log

`C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\JEFTER\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\JEFTER\Documents\node-fb-sample\node_modules\firebird
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN node-fb-sample@0.0.2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firebird@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the firebird@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JEFTER\AppData\Roaming\npm-cache\_logs\2018-12-04T20_19_01_946Z-debug.log`

**Comment by mreis1** [comment]
It looks like your envrionment is not ready to install native add-ons. 
This is the role of node-gyp. Try this: https://www.npmjs.com/package/windows-build-tools before attempting to install firebird

**Comment by mariuz** [comment]
I will add it to the readme https://www.npmjs.com/package/windows-build-tools

**Comment by Den2016** [comment]
try this https://spin.atomicobject.com/2019/03/27/node-gyp-windows/
