### ISSUE TITLE
Binding.node não é um aplicativo Win32 válido.

### ISSUE THREAD

**Issue by ramyres110** [xdenser/node-firebird-libfbclient#90]
### Ambiente
- Windows 10 Home Single Language (64 bits)
- Node v10.16.0
- NPM 6.9.0
- Python 2.7
- Ferramentas de Build do Visual Studio 2017 v15.9.14
- PATH=C:\Firebird\bin;
- Running Services
    - fbserver
    - fbguard
### Comandos executados
```cmd
> git clone https://github.com/xdenser/node-firebird-libfbclient.git
> cd node-firebird-libfbclient
> npm install
> npm install nodeunit
> node_modules\.bin\nodeunit tests\def
```

### Resultado
```bash
Error: \\?\C:\Users\ramyr\Desenvolvimento\_Nodejs\node-firebird-libfbclient\build\Release\binding.node não é um aplicativo Win32 válido.
\\?\C:\Users\ramyr\Desenvolvimento\_Nodejs\node-firebird-libfbclient\build\Release\binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\ramyr\Desenvolvimento\_Nodejs\node-firebird-libfbclient\firebird.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

### Outro caso
Em outro projeto fiz:
```cmd
> npm i firebird
```
E apenas:
```js
const fb = require("firebird");
```
e:
```cmd
> node index.js
```
Este foi o resultado:
```bash
internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-firebird\node_modules\firebird\build\Release\binding.node não é um aplicativo Win32 válido.
\\?\C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-firebird\node_modules\firebird\build\Release\binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\ramyr\Desenvolvimento\_Nodejs\try-npm-firebird\node_modules\firebird\firebird.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

## O que eu estou fazendo errado?

**Comment by mjschutz** [comment]
Olá.

Chegou a executar o node-gyp na pasta da aplicação?

npm install xdenser/node-firebird-libfbclient --build-from-source

A versão 0.1.3 do Firebird está desatualizada e essa semana mesmo foi feita a atualização do repositório.

**Comment by ramyres110** [comment]
Consegui resolver, desculpe não ter fechado a Issue... Consegui limpando todo o meu cache e inserindo a porta correta... tive de fazer algumas alterações de conexão e instalar novamente em um ambiente que não estivesse poluído por outras libs.
